name: Node.js CI

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - ./.github
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.5.0
        uses: actions/setup-node@v3
        with:
          node-version: "19.5.0"
          working-directory: ./auth
          cache: "npm"
      - name: Install Deps
        working-directory: ./auth
        run: npm i
      - name: Run Tests
        working-directory: ./auth
        run: npm test
